# -*- coding: utf-8 -*-
#
# Copyright (C) 2016-2017 Gauvain Pocentek <gauvain@pocentek.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

NO_ACCESS = 0
GUEST_ACCESS = 10
REPORTER_ACCESS = 20
DEVELOPER_ACCESS = 30
MAINTAINER_ACCESS = 40
MASTER_ACCESS = MAINTAINER_ACCESS
OWNER_ACCESS = 50

VISIBILITY_PRIVATE = 0
VISIBILITY_INTERNAL = 10
VISIBILITY_PUBLIC = 20

NOTIFICATION_LEVEL_DISABLED = "disabled"
NOTIFICATION_LEVEL_PARTICIPATING = "participating"
NOTIFICATION_LEVEL_WATCH = "watch"
NOTIFICATION_LEVEL_GLOBAL = "global"
NOTIFICATION_LEVEL_MENTION = "mention"
NOTIFICATION_LEVEL_CUSTOM = "custom"

# Search scopes
_SEARCH_SCOPE_PROJECTS = "projects"
_SEARCH_SCOPE_ISSUES = "issues"
_SEARCH_SCOPE_MERGE_REQUESTS = "merge_requests"
_SEARCH_SCOPE_MILESTONES = "milestones"
_SEARCH_SCOPE_WIKI_BLOBS = "wiki_blobs"
_SEARCH_SCOPE_COMMITS = "commits"
_SEARCH_SCOPE_BLOBS = "blobs"
_SEARCH_SCOPE_USERS = "users"

SEARCH_SCOPE_GLOBAL_PROJECTS = _SEARCH_SCOPE_PROJECTS
SEARCH_SCOPE_GLOBAL_ISSUES = _SEARCH_SCOPE_ISSUES
SEARCH_SCOPE_GLOBAL_MERGE_REQUESTS = _SEARCH_SCOPE_MERGE_REQUESTS
SEARCH_SCOPE_GLOBAL_MILESTONES = _SEARCH_SCOPE_MILESTONES
SEARCH_SCOPE_GLOBAL_SNIPPET_TITLES = "snippet_titles"
SEARCH_SCOPE_GLOBAL_WIKI_BLOBS = _SEARCH_SCOPE_WIKI_BLOBS
SEARCH_SCOPE_GLOBAL_COMMITS = _SEARCH_SCOPE_COMMITS
SEARCH_SCOPE_GLOBAL_BLOBS = _SEARCH_SCOPE_BLOBS
SEARCH_SCOPE_GLOBAL_USERS = _SEARCH_SCOPE_USERS

SEARCH_SCOPE_GROUP_PROJECTS = _SEARCH_SCOPE_PROJECTS
SEARCH_SCOPE_GROUP_ISSUES = _SEARCH_SCOPE_ISSUES
SEARCH_SCOPE_GROUP_MERGE_REQUESTS = _SEARCH_SCOPE_MERGE_REQUESTS
SEARCH_SCOPE_GROUP_MILESTONES = _SEARCH_SCOPE_MILESTONES
SEARCH_SCOPE_GROUP_WIKI_BLOBS = _SEARCH_SCOPE_WIKI_BLOBS
SEARCH_SCOPE_GROUP_COMMITS = _SEARCH_SCOPE_COMMITS
SEARCH_SCOPE_GROUP_BLOBS = _SEARCH_SCOPE_BLOBS
SEARCH_SCOPE_GROUP_USERS = _SEARCH_SCOPE_USERS

SEARCH_SCOPE_PROJECT_ISSUES = _SEARCH_SCOPE_ISSUES
SEARCH_SCOPE_PROJECT_MERGE_REQUESTS = _SEARCH_SCOPE_MERGE_REQUESTS
SEARCH_SCOPE_PROJECT_MILESTONES = _SEARCH_SCOPE_MILESTONES
SEARCH_SCOPE_PROJECT_NOTES = "notes"
SEARCH_SCOPE_PROJECT_WIKI_BLOBS = _SEARCH_SCOPE_WIKI_BLOBS
SEARCH_SCOPE_PROJECT_COMMITS = _SEARCH_SCOPE_COMMITS
SEARCH_SCOPE_PROJECT_BLOBS = _SEARCH_SCOPE_BLOBS
SEARCH_SCOPE_PROJECT_USERS = _SEARCH_SCOPE_USERS
